In [2]:
import numpy as np

When does it become 3-dimensional?
Adding a New Dimension:
The array must be reshaped or expanded to have an additional axis. For instance:
A 2D array has shape (rows, columns), e.g., (3, 3).
A 3D array has shape (depth, rows, columns) or (rows, columns, depth), depending on where the extra dimension is introduced.

Using .reshape(): Reshape the array to a 3D shape:

In [4]:
b_two_dimensional_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
b_three_dimensional_arr= b_two_dimensional_arr.reshape(1,3,3)
print(b_three_dimensional_arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
b_three_dimensional_arr.shape

(1, 3, 3)

addition, subtraction, multiplication and division

In [15]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])

# addition
addition = arr_1 + arr_2
print(addition)

#subtraction
subtrac = arr_1-arr_2
print(subtrac)

#muliplication
multiplication = (arr_1 * arr_2)
print(multiplication)

#division
#muliplication
division = (arr_1 / arr_2)
print(division)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


In [16]:
vector = np.array([1,2])
print(vector * 1.6)

[1.6 3.2]


Indexing

In [21]:
in_arr = np.array([1,2,3,4,5])
print(in_arr[2])

in_two_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(in_two_arr[2][1])

3
8


## Slicing ##

In [28]:
sl_arr = ([1,2,3,4,5])
sliced_arr = sl_arr[1:4]
print(sliced_arr)

sliced_arr = sl_arr[:3]
print(sliced_arr)

sliced_arr = sl_arr[2:]
print(sliced_arr)

sliced_arr = sl_arr[::2]
print(sliced_arr)

print(sl_arr == sl_arr[:] == sl_arr[::])

[2, 3, 4]
[1, 2, 3]
[3, 4, 5]
[1, 3, 5]
True


# slicing two dimensional array #

In [36]:
sl_two_dim = np.array(([1, 2, 3], [4,5,6], [7,8,9]))

In [42]:
sl_two_dim=sl_two_dim[0:2]
print(sl_two_dim)

slice_two_dim=sl_two_dim[1:3]
print(slice_two_dim)

slice_two_dim_cols = sl_two_dim[:, 1]
print(slice_two_dim_cols)

[[1 2 3]
 [4 5 6]]
[[4 5 6]]
[2 5]
